spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # 注意用新版驱动类
    url: jdbc:mysql://localhost:3306/music_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root  # 你的 MySQL 用户名
    password: 123456  # 你的 MySQL 密码
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.music.entity
  configuration:
    map-underscore-to-camel-case: true # 新增：开启下划线转驼峰
server:
  port: 8080